package url_patterns;

public class URLPatterns {
	public final static String HOME = "/home";
	public final static String INGREDIENTS = "/ingredients"; 
	public final static String RAWMATS = "/rawmats";
	public final static String CLIENTORDER = "/newClientOrder";
	public final static String SUPPLIERORDER = "/newSupplierOrder";
	public final static String LOGOUT = "/logOut";
	public final static String CLIENTS = "/clients";
	public final static String SUPPLIERS = "/suppliers";
	public final static String LOGIN = "/login";
	public final static String MANAGESUPPLYORDER = "/manageSupplyOrder";
	public final static String CREATEUSER = "/createUser";
	public final static String SUBMITCREATEUSERREQUEST = "/submitCreateUserRequest";
	public final static String ADDUSERTODB = "/addUserToDB";
	public final static String CHANGECODE = "/changeProductCode";
	public final static String SUBMITCHANGECODE = "/submitChangeCode";
	public final static String INVENTORY = "/inventory";
	public final static String CHANGETHRESHOLDS = "/changeThresholds";
	public final static String CHANGEINGRTHREHSOLDS = "/changeIngrThresholds";
	public final static String CREATEREPORTS = "/createReports";
	public final static String REACTIVATECLIENT = "/reactivateClient";
	public final static String REACTIVATEINGREDIENT = "/reactivateIngredient";
	public final static String PRODUCTPHYSICALCOUNT = "/productPhysicalCount";
	public final static String VIEWINACTIVEPRODUCTS = "/viewInactiveProducts";
	public final static String REACTIVATEPRODUCT = "/reactivateProduct";
	public final static String UPDATEINVENTORY = "/updateInventory";
	public final static String REMOVECLIENTORDER = "/removeClientOrder";
	public final static String REMOVESUPPLYORDER = "/removeSupplyOrder";
	public final static String ADDSTOCK = "/addStock";
	public final static String MANAGEORDERS = "/manageOrders";
	public final static String VIEWARCHIVEDCLIENTORDERS = "/viewArchivedClientOrders";
	public final static String VIEWSUPPLYORDERS = "/viewSupplyOrders";
	public final static String MANAGEREPORTS = "/manageReports";
	public final static String VIEWARCHIVEDSUPPLYORDERS = "/viewArchivedSupplyOrders";
	public final static String VIEWSUPPLIERSTOCK = "/viewSupplierStock";
	public final static String REMOVESTOCKINGREDIENT = "/removeStockIngredient";
	public final static String UPDATEUSER = "/updateUser";
	public final static String CHECKORDERSSTATUS = "/checkOrdersStatus";
}
